// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: optima/optima/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28be36ab1055a451, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28be36ab1055a451, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryEvaluateInvocableRequest struct {
	InvocableName string `protobuf:"bytes,1,opt,name=invocableName,proto3" json:"invocableName,omitempty"`
	InputData     string `protobuf:"bytes,2,opt,name=inputData,proto3" json:"inputData,omitempty"`
}

func (m *QueryEvaluateInvocableRequest) Reset()         { *m = QueryEvaluateInvocableRequest{} }
func (m *QueryEvaluateInvocableRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEvaluateInvocableRequest) ProtoMessage()    {}
func (*QueryEvaluateInvocableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28be36ab1055a451, []int{2}
}
func (m *QueryEvaluateInvocableRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEvaluateInvocableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEvaluateInvocableRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEvaluateInvocableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEvaluateInvocableRequest.Merge(m, src)
}
func (m *QueryEvaluateInvocableRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEvaluateInvocableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEvaluateInvocableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEvaluateInvocableRequest proto.InternalMessageInfo

func (m *QueryEvaluateInvocableRequest) GetInvocableName() string {
	if m != nil {
		return m.InvocableName
	}
	return ""
}

func (m *QueryEvaluateInvocableRequest) GetInputData() string {
	if m != nil {
		return m.InputData
	}
	return ""
}

type QueryEvaluateInvocableResponse struct {
	EvaluationResult string `protobuf:"bytes,1,opt,name=evaluationResult,proto3" json:"evaluationResult,omitempty"`
}

func (m *QueryEvaluateInvocableResponse) Reset()         { *m = QueryEvaluateInvocableResponse{} }
func (m *QueryEvaluateInvocableResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEvaluateInvocableResponse) ProtoMessage()    {}
func (*QueryEvaluateInvocableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28be36ab1055a451, []int{3}
}
func (m *QueryEvaluateInvocableResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEvaluateInvocableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEvaluateInvocableResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEvaluateInvocableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEvaluateInvocableResponse.Merge(m, src)
}
func (m *QueryEvaluateInvocableResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEvaluateInvocableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEvaluateInvocableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEvaluateInvocableResponse proto.InternalMessageInfo

func (m *QueryEvaluateInvocableResponse) GetEvaluationResult() string {
	if m != nil {
		return m.EvaluationResult
	}
	return ""
}

type QueryGetJobRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetJobRequest) Reset()         { *m = QueryGetJobRequest{} }
func (m *QueryGetJobRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetJobRequest) ProtoMessage()    {}
func (*QueryGetJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28be36ab1055a451, []int{4}
}
func (m *QueryGetJobRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetJobRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetJobRequest.Merge(m, src)
}
func (m *QueryGetJobRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetJobRequest proto.InternalMessageInfo

func (m *QueryGetJobRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetJobResponse struct {
	EvaluationResult string `protobuf:"bytes,1,opt,name=evaluationResult,proto3" json:"evaluationResult,omitempty"`
}

func (m *QueryGetJobResponse) Reset()         { *m = QueryGetJobResponse{} }
func (m *QueryGetJobResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetJobResponse) ProtoMessage()    {}
func (*QueryGetJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28be36ab1055a451, []int{5}
}
func (m *QueryGetJobResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetJobResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetJobResponse.Merge(m, src)
}
func (m *QueryGetJobResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetJobResponse proto.InternalMessageInfo

func (m *QueryGetJobResponse) GetEvaluationResult() string {
	if m != nil {
		return m.EvaluationResult
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "optima.optima.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "optima.optima.QueryParamsResponse")
	proto.RegisterType((*QueryEvaluateInvocableRequest)(nil), "optima.optima.QueryEvaluateInvocableRequest")
	proto.RegisterType((*QueryEvaluateInvocableResponse)(nil), "optima.optima.QueryEvaluateInvocableResponse")
	proto.RegisterType((*QueryGetJobRequest)(nil), "optima.optima.QueryGetJobRequest")
	proto.RegisterType((*QueryGetJobResponse)(nil), "optima.optima.QueryGetJobResponse")
}

func init() { proto.RegisterFile("optima/optima/query.proto", fileDescriptor_28be36ab1055a451) }

var fileDescriptor_28be36ab1055a451 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xce, 0x46, 0x0d, 0x64, 0xa4, 0x62, 0xc7, 0x06, 0xeb, 0xda, 0xac, 0x3a, 0xf6, 0x20, 0x41,
	0x33, 0xb4, 0x5e, 0xbc, 0x88, 0x58, 0x2c, 0xa2, 0x88, 0x3f, 0xf6, 0xe8, 0xa5, 0xcc, 0x26, 0x8f,
	0x65, 0x24, 0x3b, 0x6f, 0x9b, 0x99, 0x0d, 0x96, 0x92, 0x8b, 0x7f, 0x81, 0xe0, 0x1f, 0xa1, 0x47,
	0x6f, 0xfe, 0x0b, 0x3d, 0x16, 0xbc, 0x78, 0x12, 0x49, 0x04, 0xff, 0x0d, 0xc9, 0xcc, 0x44, 0xd9,
	0x64, 0x2b, 0xf6, 0xb2, 0x33, 0xfb, 0xcd, 0xf7, 0xde, 0xfb, 0xe6, 0xfb, 0x76, 0xc9, 0x15, 0xcc,
	0x8d, 0xcc, 0x04, 0xf7, 0xcb, 0x7e, 0x01, 0xc3, 0x83, 0x6e, 0x3e, 0x44, 0x83, 0x74, 0xc5, 0x61,
	0x5d, 0xb7, 0x84, 0xab, 0x22, 0x93, 0x0a, 0xb9, 0x7d, 0x3a, 0x46, 0xb8, 0x96, 0x62, 0x8a, 0x76,
	0xcb, 0x67, 0x3b, 0x8f, 0x6e, 0xa4, 0x88, 0xe9, 0x00, 0xb8, 0xc8, 0x25, 0x17, 0x4a, 0xa1, 0x11,
	0x46, 0xa2, 0xd2, 0xfe, 0xb4, 0xd3, 0x43, 0x9d, 0xa1, 0xe6, 0x89, 0xd0, 0xe0, 0xc6, 0xf1, 0xd1,
	0x56, 0x02, 0x46, 0x6c, 0xf1, 0x5c, 0xa4, 0x52, 0x59, 0xb2, 0xe7, 0x86, 0x65, 0x71, 0xb9, 0x18,
	0x8a, 0xcc, 0xf7, 0x61, 0x6b, 0x84, 0xbe, 0x9a, 0x55, 0xbf, 0xb4, 0x60, 0x0c, 0xfb, 0x05, 0x68,
	0xc3, 0x5e, 0x90, 0x4b, 0x25, 0x54, 0xe7, 0xa8, 0x34, 0xd0, 0x7b, 0xa4, 0xe1, 0x8a, 0xd7, 0x83,
	0xeb, 0xc1, 0xad, 0xf3, 0xdb, 0xad, 0x6e, 0xe9, 0x6e, 0x5d, 0x47, 0xdf, 0x69, 0x1e, 0x7d, 0xbf,
	0x56, 0xfb, 0xf4, 0xeb, 0x73, 0x27, 0x88, 0x3d, 0x9f, 0xf5, 0x48, 0xdb, 0x36, 0xdc, 0x1d, 0x89,
	0x41, 0x21, 0x0c, 0x3c, 0x51, 0x23, 0xec, 0x89, 0x64, 0x00, 0x7e, 0x22, 0xdd, 0x24, 0x2b, 0x72,
	0x8e, 0x3d, 0x17, 0x19, 0xd8, 0x09, 0xcd, 0xb8, 0x0c, 0xd2, 0x0d, 0xd2, 0x94, 0x2a, 0x2f, 0xcc,
	0x23, 0x61, 0xc4, 0x7a, 0xdd, 0x32, 0xfe, 0x02, 0xec, 0x19, 0x89, 0x4e, 0x1a, 0xe2, 0x2f, 0xd0,
	0x21, 0x17, 0xc1, 0x1d, 0x4a, 0x54, 0x31, 0xe8, 0x62, 0x60, 0xfc, 0xa0, 0x25, 0x9c, 0x6d, 0x7a,
	0x67, 0x1e, 0x83, 0x79, 0x8a, 0xc9, 0x5c, 0xe7, 0x05, 0x52, 0x97, 0x7d, 0x5b, 0x73, 0x36, 0xae,
	0xcb, 0x3e, 0x7b, 0xe8, 0x9d, 0x9a, 0xb3, 0x4e, 0x3f, 0x68, 0xfb, 0xe3, 0x19, 0x72, 0xce, 0xf6,
	0xa0, 0x8a, 0x34, 0x9c, 0x85, 0xf4, 0xc6, 0x82, 0xb3, 0xcb, 0x19, 0x85, 0xec, 0x5f, 0x14, 0x27,
	0x83, 0xb5, 0xdf, 0x7d, 0xfd, 0xf9, 0xa1, 0x7e, 0x99, 0xb6, 0x78, 0xd5, 0x27, 0x40, 0xbf, 0x04,
	0x64, 0x75, 0xc9, 0x2c, 0x7a, 0xbb, 0xaa, 0xf1, 0x49, 0xc1, 0x85, 0x77, 0xfe, 0x93, 0xed, 0x15,
	0xed, 0x5a, 0x45, 0x0f, 0xe8, 0xfd, 0x05, 0x45, 0xde, 0x15, 0xd8, 0xfb, 0x13, 0x38, 0x3f, 0x2c,
	0x65, 0x3f, 0x9e, 0xbd, 0xfb, 0xa4, 0xc7, 0xd4, 0x90, 0x86, 0x73, 0xbc, 0xda, 0xa9, 0x52, 0x66,
	0xd5, 0x4e, 0x95, 0x03, 0x63, 0x37, 0xad, 0xae, 0x36, 0xbd, 0xba, 0xa0, 0x2b, 0x05, 0xb3, 0xf7,
	0x06, 0x13, 0x7e, 0x28, 0xfb, 0xe3, 0x1d, 0x7e, 0x34, 0x89, 0x82, 0xe3, 0x49, 0x14, 0xfc, 0x98,
	0x44, 0xc1, 0xfb, 0x69, 0x54, 0x3b, 0x9e, 0x46, 0xb5, 0x6f, 0xd3, 0xa8, 0xf6, 0xba, 0xe5, 0xe9,
	0x6f, 0xe7, 0x75, 0xe6, 0x20, 0x07, 0x9d, 0x34, 0xec, 0x4f, 0x76, 0xf7, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x2c, 0x86, 0x25, 0x91, 0x1f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of EvaluateInvocable items.
	EvaluateInvocable(ctx context.Context, in *QueryEvaluateInvocableRequest, opts ...grpc.CallOption) (*QueryEvaluateInvocableResponse, error)
	// Queries a list of GetJob items.
	GetJob(ctx context.Context, in *QueryGetJobRequest, opts ...grpc.CallOption) (*QueryGetJobResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/optima.optima.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EvaluateInvocable(ctx context.Context, in *QueryEvaluateInvocableRequest, opts ...grpc.CallOption) (*QueryEvaluateInvocableResponse, error) {
	out := new(QueryEvaluateInvocableResponse)
	err := c.cc.Invoke(ctx, "/optima.optima.Query/EvaluateInvocable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetJob(ctx context.Context, in *QueryGetJobRequest, opts ...grpc.CallOption) (*QueryGetJobResponse, error) {
	out := new(QueryGetJobResponse)
	err := c.cc.Invoke(ctx, "/optima.optima.Query/GetJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of EvaluateInvocable items.
	EvaluateInvocable(context.Context, *QueryEvaluateInvocableRequest) (*QueryEvaluateInvocableResponse, error)
	// Queries a list of GetJob items.
	GetJob(context.Context, *QueryGetJobRequest) (*QueryGetJobResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) EvaluateInvocable(ctx context.Context, req *QueryEvaluateInvocableRequest) (*QueryEvaluateInvocableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateInvocable not implemented")
}
func (*UnimplementedQueryServer) GetJob(ctx context.Context, req *QueryGetJobRequest) (*QueryGetJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optima.optima.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EvaluateInvocable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEvaluateInvocableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EvaluateInvocable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optima.optima.Query/EvaluateInvocable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EvaluateInvocable(ctx, req.(*QueryEvaluateInvocableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/optima.optima.Query/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetJob(ctx, req.(*QueryGetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "optima.optima.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "EvaluateInvocable",
			Handler:    _Query_EvaluateInvocable_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _Query_GetJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optima/optima/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryEvaluateInvocableRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEvaluateInvocableRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEvaluateInvocableRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InputData) > 0 {
		i -= len(m.InputData)
		copy(dAtA[i:], m.InputData)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.InputData)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.InvocableName) > 0 {
		i -= len(m.InvocableName)
		copy(dAtA[i:], m.InvocableName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.InvocableName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEvaluateInvocableResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEvaluateInvocableResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEvaluateInvocableResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EvaluationResult) > 0 {
		i -= len(m.EvaluationResult)
		copy(dAtA[i:], m.EvaluationResult)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EvaluationResult)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetJobRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetJobRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetJobRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetJobResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetJobResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetJobResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EvaluationResult) > 0 {
		i -= len(m.EvaluationResult)
		copy(dAtA[i:], m.EvaluationResult)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EvaluationResult)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryEvaluateInvocableRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.InvocableName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.InputData)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEvaluateInvocableResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EvaluationResult)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetJobRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetJobResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EvaluationResult)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEvaluateInvocableRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEvaluateInvocableRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEvaluateInvocableRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvocableName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InvocableName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InputData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InputData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEvaluateInvocableResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEvaluateInvocableResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEvaluateInvocableResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvaluationResult", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvaluationResult = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetJobRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetJobRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetJobRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetJobResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetJobResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetJobResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvaluationResult", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvaluationResult = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
