[package]
name = "dmnengine"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dsntk-common = "0.0.9"
dsntk-evaluator = "0.0.9"
dsntk-feel = "0.0.9"
dsntk-workspace = "0.0.9"
antex = "0.0.8"
once_cell = "1.20.2"